### ISSUE TITLE
add for STYLE_CHAT

### ISSUE THREAD

**Issue by pimpmyname** [b3none/retakes-hud#10]
adding this would be nice, it shows blank text for spectators ;)

		if (StrContains(style, STYLE_CHAT) != -1)
		{
			if (clientTeam == CS_TEAM_CT || (clientTeam == CS_TEAM_T))
			{
				PrintToChat(i, "%s %s", MESSAGE_PREFIX1, message);
			}	
		}
	}
}

**Comment by B3none** [comment]
Sure, I can implement this. What text would you like the spectator to see?

**Comment by pimpmyname** [comment]
doesnt really matter, when you're spectating a person it wont show: Retake Bombsite: & Defend Bombsite: but only to the client. so the guy who spectates will receive MESSAGE_PREFIX1 only

**Comment by B3none** [comment]
I'm happy to accept a PR for this! :P

**Comment by crashzk** [comment]
@b3none I have this same problem, but I think it's better to put a check/verification, if the player is SPEC you don't receive any message.

![Screenshot_1](https://user-images.githubusercontent.com/32937653/140616671-cb6b42c7-2a05-4ea1-8cc7-67b7f86f2163.png)
