### ISSUE TITLE
Help message retake

### ISSUE THREAD

**Issue by chulicoxd** [b3none/retakes-hud#14]
Hi, how about I think I arrived too late to ask you about something that I can't fix, is it with the hud or I don't know if that will be the problem, the question is the following once the bomb is planted the messages to the ct of where it is placed the pump only comes out in the middle of the screen in gray and I would love that it also appears in the bottom left in the global chat so you can read where the bomb was also placed I can not see it on my server.

**Comment by chulicoxd** [comment]
**Really the problem is here retake.phrases.txt
"RetakeSiteMessage"
	{
		"#format"		"{1:s},{2:d},{3:d}"
		"en"			"Retake {GREEN}{1}: {LIGHT_RED}{2} Ts {NORMAL}vs {PURPLE}{3} CTs"
	}
example msg: (retake b: 1ts vs 1cts)
-----------------------------------------------------------------------------------------------------------
and the message that I would like to leave is this:
example msg: (retake b-b-b: 1ts vs 1cts)**

**Comment by B3none** [comment]
Hey @chulicoxd, that certainly looks do-able!

**Comment by borzaka** [comment]
Just modify that message to:
`"Retake {GREEN}{1}-{1}-{1}: {LIGHT_RED}{2} Ts {NORMAL}vs {PURPLE}{3} CTs"`
