### ISSUE TITLE
Unable to compile with stable/dev Sourcemod

### ISSUE THREAD

**Issue by q4-bi** [b3none/retakes-hud#25]
//SourceMod Batch Compiler
// by the SourceMod Dev Team

//// retakes_hud.sp
//
// C:\Users\Brendan\Desktop\addons\sourcemod\scripting\retakes_hud.sp(140) : error 047: array sizes do not match, or destination array is too small
//
// 1 Error.
//
// Compilation Time: 1.22 sec
// ----------------------------------------

Press enter to exit ...

**Comment by B3none** [comment]
Can you test this on the latest official release of sourcemod

**Comment by crashzk** [comment]
@b3none I tested with the latest official sourcemod version, stable version and same error.
```
//SourceMod Batch Compiler
// by the SourceMod Dev Team


//// retakes_hud.sp
//
// D:\Google Drive\ZK Servidores\Servidores CSGO\Editar Plugins\addons\sourcemod\scripting\retakes_hud.sp(140) : error 047: array sizes do not match, or destination array is too small
//
// 1 Error.
//
// Compilation Time: 0,36 sec
// ----------------------------------------

Press enter to exit ...
```

**Comment by B3none** [comment]
Can you test compilation with the latest code change - https://github.com/B3none/retakes-hud/commit/7c2877cdfd847715375c26521a3ad6d9677b8029

**Comment by crashzk** [comment]
It compiled, it only showed a warning, but it compiled without problems. I'll be testing it now and report anything.

Thank you for now!
