### ISSUE TITLE
log error

### ISSUE THREAD

**Issue by ByKyTa** [b3none/retakes-hud#3]
L 04/02/2019 - 17:54:30: SourceMod error session started
L 04/02/2019 - 17:54:30: Info (map "de_cache") (file "C:\Users\ByKyTa\Desktop\Retaker\csgo\addons\sourcemod\logs\errors_20190402.log")
L 04/02/2019 - 17:54:30: [SM] Exception reported: Client index -1 is invalid
L 04/02/2019 - 17:54:30: [SM] Blaming: retakes-hud.smx
L 04/02/2019 - 17:54:30: [SM] Call stack trace:
L 04/02/2019 - 17:54:30: [SM]   [0] GetClientAbsOrigin
L 04/02/2019 - 17:54:30: [SM]   [1] Line 149, retakes-hud.sp::GetNearestBombsite
L 04/02/2019 - 17:54:30: [SM]   [2] Line 83, retakes-hud.sp::Event_OnRoundStart
L 04/02/2019 - 17:54:30: [SM] Exception reported: Client index -1 is invalid
L 04/02/2019 - 17:54:30: [SM] Blaming: retakes-hud.smx
L 04/02/2019 - 17:54:30: [SM] Call stack trace:
L 04/02/2019 - 17:54:30: [SM]   [0] GetClientAbsOrigin
L 04/02/2019 - 17:54:30: [SM]   [1] Line 149, retakes-hud.sp::GetNearestBombsite
L 04/02/2019 - 17:54:30: [SM]   [2] Line 83, retakes-hud.sp::Event_OnRoundStart
L 04/02/2019 - 17:54:42: [SM] Exception reported: Invalid convar handle 0 (error 4)
L 04/02/2019 - 17:54:42: [SM] Blaming: retakes-hud.smx
L 04/02/2019 - 17:54:42: [SM] Call stack trace:
L 04/02/2019 - 17:54:42: [SM]   [0] GetConVarBool
L 04/02/2019 - 17:54:42: [SM]   [1] Line 68, retakes-hud.sp::OnConfigsExecuted
L 04/02/2019 - 17:54:43: Error log file session closed.
L 04/02/2019 - 17:54:43: SourceMod error session started
L 04/02/2019 - 17:54:43: Info (map "de_cache") (file "C:\Users\ByKyTa\Desktop\Retaker\csgo\addons\sourcemod\logs\errors_20190402.log")
L 04/02/2019 - 17:54:43: [SM] Exception reported: Client index -1 is invalid
L 04/02/2019 - 17:54:43: [SM] Blaming: retakes-hud.smx
L 04/02/2019 - 17:54:43: [SM] Call stack trace:
L 04/02/2019 - 17:54:43: [SM]   [0] GetClientAbsOrigin
L 04/02/2019 - 17:54:43: [SM]   [1] Line 149, retakes-hud.sp::GetNearestBombsite
L 04/02/2019 - 17:54:43: [SM]   [2] Line 83, retakes-hud.sp::Event_OnRoundStart
L 04/02/2019 - 17:54:43: [SM] Exception reported: Client index -1 is invalid
L 04/02/2019 - 17:54:43: [SM] Blaming: retakes-hud.smx
L 04/02/2019 - 17:54:43: [SM] Call stack trace:
L 04/02/2019 - 17:54:43: [SM]   [0] GetClientAbsOrigin
L 04/02/2019 - 17:54:43: [SM]   [1] Line 149, retakes-hud.sp::GetNearestBombsite
L 04/02/2019 - 17:54:43: [SM]   [2] Line 83, retakes-hud.sp::Event_OnRoundStart
L 04/02/2019 - 17:54:43: [SM] Exception reported: Invalid convar handle 0 (error 4)
L 04/02/2019 - 17:54:43: [SM] Blaming: retakes-hud.smx
L 04/02/2019 - 17:54:43: [SM] Call stack trace:
L 04/02/2019 - 17:54:43: [SM]   [0] GetConVarBool
L 04/02/2019 - 17:54:43: [SM]   [1] Line 68, retakes-hud.sp::OnConfigsExecuted
L 04/02/2019 - 17:54:44: [SM] Exception reported: Client index -1 is invalid
L 04/02/2019 - 17:54:44: [SM] Blaming: retakes-hud.smx
L 04/02/2019 - 17:54:44: [SM] Call stack trace:
L 04/02/2019 - 17:54:44: [SM]   [0] GetClientAbsOrigin
L 04/02/2019 - 17:54:44: [SM]   [1] Line 149, retakes-hud.sp::GetNearestBombsite
L 04/02/2019 - 17:54:44: [SM]   [2] Line 83, retakes-hud.sp::Event_OnRoundStart

**Comment by B3none** [comment]
I've uploaded a fix, please compile the latest code and try it out. Thanks for using the plugin! :)
