### ISSUE TITLE
[Feature Request] Toggle enabled cvar

### ISSUE THREAD

**Issue by thboss** [b3none/retakes-hud#5]
can you add cvar to enable/disable hud message?
it still appear even if retakes disabled!!

**Comment by B3none** [comment]
That’s a good suggestion. I was thinking I could add that as well as a check to see whether Retakes in enabled if that’s easier for you?

**Comment by thboss** [comment]
yes, also good idea

**Comment by B3none** [comment]
https://github.com/b3none/retakes-hud/commit/470be8748fcf11f416687234432f2db431f75c39
