### ISSUE TITLE
Bombsite Message PrintHintText

### ISSUE THREAD

**Issue by lazhoroni** [b3none/retakes-hud#7]
Can you show the bombsite as a message for 6 seconds?
You can repeat every second. When you have finished for 6 seconds, you end the message.

public void OnPluginStart()
{
    HookEvent("round_start", event_start);
}
public Action event_start(Event event, char[] name, bool dontBroadcast)
{
    gH_Timer = CreateTimer(1.0, Timer_Second, _, TIMER_REPEAT);
}
    		if (gI_Time < 6)
    		{
    			PrintHintTextToAll("<font size='70'>DEFEND: </font><font size='70' color='#FF0000'>%s</font>", bombsite);
    		}
    		else
    		{
    			TryClearData();
    		}

**Comment by B3none** [comment]
Hey, I’m happy to accept a PR with the changes. You’ll need to put this behind a cvar

**Comment by lazhoroni** [comment]
I can't see the hud message when the round starts. If the hinttext message goes away, everyone will see more comfortably in the middle of the screen.
it might be right to change the message when the bomb was set.
PrintHintText(i, "<font size='70' color='#FF0000'>%T</font>"...

**Comment by lazhoroni** [comment]
Can you show the retakeside message in the hinttext message for 6 seconds without the bomb message being displayed?
