### ISSUE TITLE
hud not work

### ISSUE THREAD

**Issue by thboss** [b3none/retakes-hud#9]
hud not work when change map retakes off to retakes on map
and I check cvars
sm_retakes_enabled 1
sm_retakes_hud_enabled 1
sm 1.9
retakes plugins
  57 "CS:GO Retakes: site picker" (0.3.4) by splewis
  58 "CS:GO Retakes" (0.3.4) by splewis
  59 "CS:GO Retakes: standard weapon allocator" (0.3.4) by splewis
  60 "[Retakes] Autoplant" (2.1.1) by B3none
  61 "[Retakes] Bombsite HUD" (2.5.0) by B3none
  62 "[Retakes] VIP Queue" (1.0.0) by B3none

**Comment by B3none** [comment]
Looking into this in the next few days. In the meantime I'd suggest downloading the latest version of [Retakes Autoplant](https://github.com/b3none/retakes-autoplant)

**Comment by B3none** [comment]
This is working for me. Are you getting any console errors?

**Comment by B3none** [comment]
Since this is a stale issue I'm going to close it.

**Comment by thboss** [comment]
sorry, I saw it now, the problem I think is conflict another plugin use hud messages
